<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
تعریف آرایه
    </font>
</h1>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
ابتدا کد زیر را اجرا کنید تا ضمن اطمینان از نصب موفقیت آمیز نامپای از نسخه نصب شده مطلع شوید.
    </font>
</p>

In [18]:
# عموما به طور قراردادی از کتابخانهٔ نامپای به این شکل استفاده می‌شود
import numpy as np 
np.__version__ 

'2.1.1'

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در این دوره از نسخه 2.1.1 نامپای استفاده شده است و خروجی‌هایی که خواهید دید، با این نسخه تولید شده است.
    </font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc"><a href="https://numpy.org/doc/stable/reference/routines.array-creation.html" target="_blank" style="color:#0099cc">🔗</a>ساخت آرایه
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    یکی از راه‌های ساخت آرایه نامپای ورودی دادن لیست پایتون به تابع <code>array</code> نامپای است.
    در کدهای زیر نمونه‌هایی از این نوع ایجاد آرایه را می‌بینید.
</font>
</p>

In [19]:
# آرایه یک بعدی شامل 3 عدد
np.array([1, 2, 3])

array([1, 2, 3])

In [20]:
# آرایه دو بعدی 2*3 شامل 6 عدد 
np.array([[1, 2], 
         [3, 4],
         [5, 6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
# آرایه سه بعدی 2*2*2 شامل 8 رشته
np.array([[['000', '001'], ['010', '011']], 
          [['100', '101'], ['110', '111']]])
# dtype نوع خانه‌های آرایه را نشان می‌دهد
# <U3 که نوع این آرایه می‌شود به معنای رشته یونی‌کد 3 حرفی است 

array([[['000', '001'],
        ['010', '011']],

       [['100', '101'],
        ['110', '111']]], dtype='<U3')

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
یک راه دیگر برای ساخت آراه نامپای، استفاده از توابع داخلی نامپای است که چند نمونه از آن را در کدهای زیر می‌بینید.
    </font>
</p>

In [22]:
# آرایه یک بعدی شامل 3 عدد حقیقی برابر صفر
np.zeros(3)

array([0., 0., 0.])

In [23]:
# آرایه دو بعدی 3*2 شامل 6 عدد حقیقی برابر یک
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [24]:
# آرایه دو بعدی 2*3 شامل 6 رشته متنی '#' یکسان
np.full((3, 2), '#') 

array([['#', '#'],
       ['#', '#'],
       ['#', '#']], dtype='<U1')

In [25]:
# آرایه یک بعدی شامل اعداد صحیح پیش از 15 با شروع از 0 و با فاصله 4
np.arange(0, 15, 4) 

array([ 0,  4,  8, 12])

In [26]:
# آرایه یک بعدی شامل 5 عدد حقیقی در بازه 0 تا 20 (شامل این دو) با فاصله برابر
np.linspace(0, 20, 5) 

array([ 0.,  5., 10., 15., 20.])

In [27]:
# آرایه دو بعدی 3*3 متناظر با ماتریس همانی (قطر 1 و باقی خانه‌ها 0)
np.eye(3) 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [28]:
# آرایه یک بعدی شامل 3 عدد نامشخص (بسته به مقدار داخل حافظه)
np.empty(3) 

array([1., 1., 1.])

In [29]:
# آرایه یک بعدی شامل 3 عدد تصادفی از توزیع یکنواخت بین 0 و 1
np.random.random(3) 

array([0.56436054, 0.39880044, 0.49816485])

In [30]:
# آرایه دو بعدی 3*3 شامل اعداد صحیح تصادفی بین 0 تا 9 
np.random.randint(0, 10, (3, 3)) 

array([[1, 4, 7],
       [9, 2, 9],
       [1, 8, 0]], dtype=int32)

In [31]:
# آرایه دو بعدی 3*2 شامل اعداد تصادفی از توزیع نرمال با میانگین 0 و واریانس 1 
np.random.normal(0, 1, (2, 3)) 

array([[-0.57873753,  0.2058292 , -0.41225812],
       [ 0.04365235, -0.38477397, -0.87510006]])

In [32]:
# آرایه دو بعدی 3*2 شامل اعداد صحیح تصادفی بین 0 تا 10 
a = np.random.randint(0, 10, (2, 3))
# آرایه پر از 3 با ابعاد مشابه آرایه ورودی (3*2)
np.full_like(a, 3) 

array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
نوع داده
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
    در کدهای زیر، چگونگی تعیین نوع داده آرایه با تعیین <code>dtype</code> هنگام ساخت را می‌بینید.    </font>
</p>

In [33]:
# نوع مقدار بولی
np.array([False, True], dtype='bool_') 
# کاراکتر _ برای اشاره به نوع داخل نامپای است اما می‌توان آن را برداشت

array([False,  True])

In [34]:
# نوع عدد صحیح (عدد سوم تبدیل به 3 می‌شود)
np.array([1, 2, 3.14], dtype='int_') 

array([1, 2, 3])

In [35]:
# نوع عدد حقیقی 128 بیتی
np.array([2.71828182845, 3.14159265359], dtype='float128') 

TypeError: data type 'float128' not understood

In [ ]:
# نوع عدد صحیح نامنفی 8 بیتی
np.array([255], dtype='uint8') 

array([255], dtype=uint8)

In [ ]:
# نوع رشته
np.array(['Hello', 'World'], dtype='str_') 

array(['Hello', 'World'], dtype='<U5')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazir" color="#0099cc">
مشخصه‌ها
    </font>
</h2>

<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazir" size=3>
در کدهای زیر، چند مثال از مشخصه‌های آرایه را مشاهده می‌کنید.
</p>

In [ ]:
a = np.array([[1, 2],
             [3, 4],
             [5, 6]], dtype='float64')
print(a)
print('number of dimensions:', a.ndim)  # تعداد ابعاد آرایه
print('shape:', a.shape)                # اندازه ابعاد آرایه
print('size:', a.size)                  # تعداد خانه‌های آرایه
print('dtype:', a.dtype)                # نوع داده آرایه

[[1. 2.]
 [3. 4.]
 [5. 6.]]
number of dimensions: 2
shape: (3, 2)
size: 6
dtype: float64


In [ ]:
c = np.array(['h', 'e', 'l', 'l', 'o'])
print("c is:",c)
print("c each item size is:",c.itemsize, 'bytes')   # تعداد بایت برای هر خانه آرایه
print("c total item size is:",c.nbytes, 'bytes')    # تعداد بایت برای کل آرایه

c is: ['h' 'e' 'l' 'l' 'o']
c each item size is: 4 bytes
c total item size is: 20 bytes
